#!/usr/bin/env python3
"""Fetch set28 .kicad_pcb sources listed in manifest_set28.json (raw download).

set28 began as the hwidvorakinfo (Daniel Dvorak) batch -- a single-designer
survey of that author's 22 public repos, of which only 3 ship a
.kicad_pcb at all (the rest are firmware-only STM32 Eclipse projects).
BEASTH7_01 was rejected by validate_candidate.py as pre-KiCad-6 format
(20171130, ships a v5 .pro rather than a .kicad_pro), leaving two:
a 2 GHz active scope probe (RF/analog, few nets but tight geometry) and
a 218-footprint smart agricultural switch (mains-side power + MCU).

mez_rx joined later from a DIFFERENT source: a user-submitted board
attached to issue #614 by ughstudios (Daniel Gleason), who reported the
router could not complete it. It is the first ARCHIVE-sourced entry
(a .zip attachment, not a raw repo URL -- see archive_url/archive_member)
and the corpus's hardest board to date: 8 layers, a 400-ball 0.8mm-pitch
FPGA, a real .kicad_dru DFM ruleset, and 91.1% completion against a
corpus median of 100%. It has NEVER been human-routed, so boards_set28/
mez_rx.kicad_pcb is a DEGENERATE reference (0 segments/0 vias):
compare_to_original and the DRC-delta-vs-original are meaningless for it.

storm_tracker (solderable/storm-tracker-hardware) joined 2026-08-13 at
Andy's request: a 4-layer 36.5x69mm ESP32-C6-MINI-1U lightning detector
(AS3935 + 1.54" e-paper over a 24-pin 0.5mm FFC, USB-C, battery charger).
Small but dense -- 342 vias in 2500mm2, a 0.13mm fab floor -- and one of
only two corpus boards with a real .kicad_dru; unlike mez_rx's DFM
ruleset, its single rule is CONDITIONED on a netclass
(A.NetClass == '90R_DP' && B.NetName == 'GND'), and its USB pair is
netclass-assigned by PATTERN (*USB_D* -> 90R_DP). Fully human-routed, so
unlike mez_rx it is a usable compare_to_original reference.

Downloads each board and its sibling project files -- the .kicad_pro (DRC floor,
#441) and the .kicad_dru (per-layer clearance rules, #498) --
into $STRESS_DIR/sources/github_set28/. After fetching, run `bash prep_set28.sh`
(needs KiCad's bundled python / pcbnew) to produce boards_set28/ (routed
reference) + boards_unrouted_set28/ (stripped).

  python3 fetch_set28.py
  bash prep_set28.sh

Auto-generated by assemble_corpus.py.
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
STRESS = Path(os.environ.get("STRESS_DIR", str(Path.home() / "Documents/kicad_stress_test")))
MANIFEST = HERE / "manifest_set28.json"


def fetch_archive(b, dest):
    """Board shipped as a .zip (e.g. attached to a GitHub issue) rather than a
    raw .kicad_pcb URL. Download the archive, extract `archive_member` as the
    board, and take its siblings from the SAME directory inside the archive --
    the .kicad_pro (DRC floor, #441) and .kicad_dru (per-layer clearance, #498)
    travel with it. Returns True on success.
    """
    with tempfile.TemporaryDirectory() as td:
        zp = Path(td) / "src.zip"
        r = subprocess.run(["curl", "-sL", "--fail", b["archive_url"], "-o", str(zp)],
                           capture_output=True)
        if r.returncode != 0 or not zp.exists() or zp.stat().st_size == 0:
            return False
        try:
            with zipfile.ZipFile(zp) as z:
                z.extractall(Path(td) / "x")
        except zipfile.BadZipFile:
            return False
        member = Path(td) / "x" / b["archive_member"]
        if not member.exists():
            return False
        shutil.copy(member, dest)
        for ext in (".kicad_pro", ".kicad_dru"):
            sib = member.with_suffix(ext)
            if sib.exists():
                shutil.copy(sib, dest.with_suffix(ext))
        return True


def main():
    boards = json.loads(MANIFEST.read_text())
    out_dir = STRESS / "sources/github_set28"
    out_dir.mkdir(parents=True, exist_ok=True)
    ok = 0
    for b in boards:
        dest = out_dir / Path(b["file"]).name
        if b.get("archive_url"):
            if fetch_archive(b, dest):
                ok += 1
                print(f"  OK  {b['repo']:42} {dest.stat().st_size // 1024}KB  "
                      f"[{b.get('tier','?')}] (archive)")
            else:
                print(f"  FAIL {b['repo']}  <- {b['archive_url']}")
            continue
        r = subprocess.run(["curl", "-sL", "--fail", b["raw_url"], "-o", str(dest)],
                           capture_output=True)
        if r.returncode != 0 or not dest.exists() or dest.stat().st_size == 0:
            print(f"  FAIL {b['repo']}  <- {b['raw_url']}")
            continue
        # siblings: never drop them. Without the .kicad_pro a board resolves its
        # DRC floor from the STOCK netclass (#441); without the .kicad_dru every
        # routing step and check_drc lose the per-layer/conditioned clearance
        # rules that OUTRANK --clearance (#498). A 404 under --fail can still
        # leave a zero-byte file, which reads as "rules present, none" -- drop it.
        for ext in (".kicad_pro", ".kicad_dru"):
            sib = dest.with_suffix(ext)
            subprocess.run(["curl", "-sL", "--fail",
                            b["raw_url"][: -len(".kicad_pcb")] + ext,
                            "-o", str(sib)], capture_output=True)
            if sib.exists() and sib.stat().st_size == 0:
                sib.unlink()
        ok += 1
        print(f"  OK  {b['repo']:42} {dest.stat().st_size // 1024}KB  [{b.get('tier','?')}]")
    print(f"\n{ok}/{len(boards)} set28 sources -> {out_dir}")
    return 0 if ok == len(boards) else 1


if __name__ == "__main__":
    sys.exit(main())
