#!/bin/bash
# Normalize+strip every set27 board (one pcbnew process each, segfault-safe).
# Reuses prep_set2.py (generic: <src> <routed_dst> <stripped_dst>).
#   stripped, unrouted boards -> boards_unrouted_set27/
#   normalized routed reference + .kicad_pro -> boards_set27/
# Auto-generated by assemble_corpus.py. Sources are modern KiCad (v6+).
set -u
SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STRESS="${STRESS_DIR:-$HOME/Documents/kicad_stress_test}"
SRC="$STRESS/sources/github_set27"
KPY="${KICAD_PYTHON:-/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3}"
PREP="$SELF/prep_set2.py"
mkdir -p "$STRESS/boards_unrouted_set27" "$STRESS/boards_set27"

# short-name | source-filename-fragment (unique within github_set27/)
MAP=(
  "arty_mpw_tester|arty_mpw_tester"
  "audio_latency_tester|audio_latency_tester"
  "dual_ipex_csi_interposer|dual_ipex_csi_interposer"
  "gmsl_deserializer|gmsl_deserializer"
  "jetson_agx_csi_adapter|jetson_agx_csi_adapter"
  "job_storage_exp|job_storage_exp"
  "ov9281_dual_cam|ov9281_dual_cam"
  "usbc_power_adapter|usbc_power_adapter"
  "video_latency_probe|video_latency_probe"
)

for entry in "${MAP[@]}"; do
  IFS='|' read -r name frag <<< "$entry"
  srcfile=$(find "$SRC" -maxdepth 1 -name '*.kicad_pcb' -name "*${frag}*" | head -1)
  if [ -z "$srcfile" ]; then echo "MISS $name (frag '$frag')"; continue; fi
  echo "== $name <- $(basename "$srcfile")"
  "$KPY" "$PREP" "$srcfile" "$STRESS/boards_set27/$name.kicad_pcb" \
         "$STRESS/boards_unrouted_set27/$name.kicad_pcb" 2>/dev/null || echo "  FAIL $name"
  profile="${srcfile%.kicad_pcb}.kicad_pro"
  [ -f "$profile" ] && cp "$profile" "$STRESS/boards_set27/$name.kicad_pro"
done
echo "Done. stripped -> boards_unrouted_set27/ ; routed reference -> boards_set27/"
