#!/bin/bash
# Normalize+strip every set3monster board (one pcbnew process each, segfault-safe).
# Reuses prep_set2.py (generic: <src> <routed_dst> <stripped_dst>).
#   stripped, unrouted boards -> boards_unrouted_set3monster/
#   normalized routed reference + .kicad_pro -> boards_set3monster/
# Auto-generated by assemble_corpus.py. Sources are modern KiCad (v6+).
set -u
SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STRESS="${STRESS_DIR:-$HOME/Documents/kicad_stress_test}"
SRC="$STRESS/sources/github_set3monster"
KPY="${KICAD_PYTHON:-/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3}"
PREP="$SELF/prep_set2.py"
mkdir -p "$STRESS/boards_unrouted_set3monster" "$STRESS/boards_set3monster"

# short-name | source-filename-fragment (unique within github_set3monster/)
MAP=(
  "dcscm_osm_carrier|dcscm_osm_carrier"
  "ddr4_rdimm_tester|ddr4_rdimm_tester"
  "ddr5_rdimm_tester|ddr5_rdimm_tester"
  "ddr5_sodimm_tester|ddr5_sodimm_tester"
  "jetson_agx_thor_bb|jetson_agx_thor_bb"
  "kintex_410t_devboard|kintex_410t_devboard"
  "lora_cubesat_cm|lora_cubesat_cm"
  "osm_l_bmc_som|osm_l_bmc_som"
  "polarfire_som|polarfire_som"
  "stm32h7_hdmi|stm32h7_hdmi"
)

for entry in "${MAP[@]}"; do
  IFS='|' read -r name frag <<< "$entry"
  srcfile=$(find "$SRC" -maxdepth 1 -name '*.kicad_pcb' -name "*${frag}*" | head -1)
  if [ -z "$srcfile" ]; then echo "MISS $name (frag '$frag')"; continue; fi
  echo "== $name <- $(basename "$srcfile")"
  "$KPY" "$PREP" "$srcfile" "$STRESS/boards_set3monster/$name.kicad_pcb" \
         "$STRESS/boards_unrouted_set3monster/$name.kicad_pcb" 2>/dev/null || echo "  FAIL $name"
  profile="${srcfile%.kicad_pcb}.kicad_pro"
  [ -f "$profile" ] && cp "$profile" "$STRESS/boards_set3monster/$name.kicad_pro"
done
echo "Done. stripped -> boards_unrouted_set3monster/ ; routed reference -> boards_set3monster/"
