#!/bin/bash
# Normalize+strip every set26 board (one pcbnew process each, segfault-safe).
# Reuses prep_set2.py (generic: <src> <routed_dst> <stripped_dst>).
#   stripped, unrouted boards -> boards_unrouted_set26/
#   normalized routed reference + .kicad_pro -> boards_set26/
# Auto-generated by assemble_corpus.py. Sources are modern KiCad (v6+).
set -u
SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STRESS="${STRESS_DIR:-$HOME/Documents/kicad_stress_test}"
SRC="$STRESS/sources/github_set26"
KPY="${KICAD_PYTHON:-/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3}"
PREP="$SELF/prep_set2.py"
mkdir -p "$STRESS/boards_unrouted_set26" "$STRESS/boards_set26"

# short-name | source-filename-fragment (unique within github_set26/)
MAP=(
  "cvbs_mipi_bridge|cvbs_mipi_bridge"
  "d1600e_psu_breakout|d1600e_psu_breakout"
  "dcscm_breakout|dcscm_breakout"
  "environment_sensor|environment_sensor"
  "framos_csi_adapter|framos_csi_adapter"
  "ftdi_debug_toolkit|ftdi_debug_toolkit"
  "ict_baseboard|ict_baseboard"
  "ir_irradiance_probe|ir_irradiance_probe"
  "job_ict_bottom|job_ict_bottom"
  "led_panel_prog|led_panel_prog"
  "lz1_led_driver|lz1_led_driver"
  "myra_sip_interposer|myra_sip_interposer"
  "pmod_i3c_sensor|pmod_i3c_sensor"
  "sdi_fiber_adapter|sdi_fiber_adapter"
  "stm32h7_renode_ref|stm32h7_renode_ref"
)

for entry in "${MAP[@]}"; do
  IFS='|' read -r name frag <<< "$entry"
  srcfile=$(find "$SRC" -maxdepth 1 -name '*.kicad_pcb' -name "*${frag}*" | head -1)
  if [ -z "$srcfile" ]; then echo "MISS $name (frag '$frag')"; continue; fi
  echo "== $name <- $(basename "$srcfile")"
  "$KPY" "$PREP" "$srcfile" "$STRESS/boards_set26/$name.kicad_pcb" \
         "$STRESS/boards_unrouted_set26/$name.kicad_pcb" 2>/dev/null || echo "  FAIL $name"
  profile="${srcfile%.kicad_pcb}.kicad_pro"
  [ -f "$profile" ] && cp "$profile" "$STRESS/boards_set26/$name.kicad_pro"
done
echo "Done. stripped -> boards_unrouted_set26/ ; routed reference -> boards_set26/"
