#!/bin/bash
# Normalize+strip every set28 board (one pcbnew process each, segfault-safe).
# Reuses prep_set2.py (generic: <src> <routed_dst> <stripped_dst>).
#   stripped, unrouted boards -> boards_unrouted_set28/
#   normalized routed reference + .kicad_pro -> boards_set28/
# Auto-generated by assemble_corpus.py. Sources are modern KiCad (v6+).
set -u
SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STRESS="${STRESS_DIR:-$HOME/Documents/kicad_stress_test}"
SRC="$STRESS/sources/github_set28"
KPY="${KICAD_PYTHON:-/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3}"
PREP="$SELF/prep_set2.py"
mkdir -p "$STRESS/boards_unrouted_set28" "$STRESS/boards_set28"

# short-name | source-filename-fragment (unique within github_set28/)
MAP=(
  "act_probe_2ghz|act_probe_2ghz"
  "agri_smart_switch|agri_smart_switch"
  "mez_rx|mez_rx"
  "storm_tracker|storm_tracker"
)

for entry in "${MAP[@]}"; do
  IFS='|' read -r name frag <<< "$entry"
  srcfile=$(find "$SRC" -maxdepth 1 -name '*.kicad_pcb' -name "*${frag}*" | head -1)
  if [ -z "$srcfile" ]; then echo "MISS $name (frag '$frag')"; continue; fi
  echo "== $name <- $(basename "$srcfile")"
  "$KPY" "$PREP" "$srcfile" "$STRESS/boards_set28/$name.kicad_pcb" \
         "$STRESS/boards_unrouted_set28/$name.kicad_pcb" 2>/dev/null || echo "  FAIL $name"
  profile="${srcfile%.kicad_pcb}.kicad_pro"
  [ -f "$profile" ] && cp "$profile" "$STRESS/boards_set28/$name.kicad_pro"
done
echo "Done. stripped -> boards_unrouted_set28/ ; routed reference -> boards_set28/"
